spring.application.name=self-storage

# ===============================
# SQL SERVER DATABASE
# ===============================

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SelfStorageFacilityDB;encrypt=true;trustServerCertificate=true

spring.datasource.username=sa
spring.datasource.password=12345

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
app.jwt.secret=safebox-local-development-only-signing-key-not-for-production-2026
app.jwt.expiration=3600000

